print("______________________________________________________________________________")
print("|                              CO-OPERATIVE BANK                             |")
print("|                                  CBD BRANCH                                |")
print("|                                 8TH Feb 2023                               |")
print("| first name: Mark                                                           |")
print("| second name:Mirauri                                                        |")
print("| account.no: 123456789345                                                   |")
print("| account.bal:ksh2400.50                                                     |")
print("|                                                                            |")
print("| Co-operative the listening and learing partner                             |")
print("|____________________________________________________________________________|")
