s_name = input("What is your second name?")
print("my name is",s_name)
f_name = input("what is your first name?")
print("My name is ",f_name)
f_num = input("enter first number")
s_num = input("enter the second number")
sum_num = int(f_num) + int(s_num)
#convert the string into integers
print("the sum of the numbers:",sum_num)
diff_num = int(f_num) - int(s_num)
print("the difference of the numbers is",diff_num)
quo_num = int(f_num) / int(s_num)
print("the quotiet of the numbers is",quo_num)
prod_num = int(f_num) * int(s_num)
print("the answer is",prod_num)
